name: Scott Haas
favicon: null
layout_spectrum: 0.24955
typography_spectrum: 0.49456
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ca191f'
    - '#b4b3af'
    - '#7e7a9b'
    - '#3c130d'
    - '#5a4d57'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
